# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm install yarn
    - run: yarn && yarn build
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build
      - name: Deploy artifact
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{secrets.SSH_HOST}}
          privateKey: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          local: './build'
          remote: '/var/www/html/chat.brianmatthewsmith.com'